name: Maven CI
on:
  push:
    branches: [ main, 'feature/**', 'refactor/**', 'fix/**', 'docs/**', 'bench/**' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '23'
          cache: maven
      - name: Test
        run: mvn -B -q -DskipITs clean test
      - name: Package
        run: mvn -B -q -DskipTests package
